### ISSUE TITLE
Add a "source" tag to differentiate source proxies

### ISSUE THREAD

**Issue by SebastienChauvin** [SRGSSR/jass#1]
We could run each mitmproxy with a tag to be propagated and store this tag in the inputrequest so that we can easily filter requests done from within SPA team from requests caught from SRF sub networks for instance.

**Comment by onekiloparsec** [comment]
Why not making API access keys then? Or does it smell antipattern?...

**Comment by SebastienChauvin** [comment]
Mhh no, I was not clear enough. My proposal is to add a way to
differentiate between each "access point", it will be in complement to
device local IP, OS version and application name to identify each request.

Le mar. 6 oct. 2015 à 16:19, Cédric Foellmi notifications@github.com a
écrit :
